export const Gender = [
  {
    id: 1,
    username: "MAN",
    btntext: "ManClothingCollection",
    thumbnail:
      "https://images.pexels.com/photos/6050430/pexels-photo-6050430.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 2,
    username: "WOMAN",
    btntext: "WomanClothingCollection",
    thumbnail:
      "https://images.pexels.com/photos/5418889/pexels-photo-5418889.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
  },
  {
    id: 3,
    username: "KIDS",
    btntext: "KidsClothingCollection",
    thumbnail:
      "https://images.pexels.com/photos/1619815/pexels-photo-1619815.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

const Home = [
  {
    id: 1,
    title: "Women’s Sheepskin Coats Archives",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "puma",
    sub_category: "Man",
    category: "shirt",
    thumbnail:
      "https://images.pexels.com/photos/27663337/pexels-photo-27663337/free-photo-of-a-woman-in-a-pink-dress-walking-on-the-beach.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
    images: [
      "https://images.pexels.com/photos/2755612/pexels-photo-2755612.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/1/2.jpg",
      "https://cdn.dummyjson.com/product-images/1/3.jpg",
      "https://cdn.dummyjson.com/product-images/1/4.jpg",
      "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    ],
  },
  {
    id: 2,
    title: "Rayane Ketlyn Stylish Fashion Outfits",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 24.94,
    rating: 4.44,
    stock: 34,
    brand: "Adidas",
    sub_category: "Woman",
    category: "tshirt",
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/3679044/pexels-photo-3679044.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/2/2.jpg",
      "https://cdn.dummyjson.com/product-images/2/3.jpg",
      "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
    ],
  },
  {
    id: 3,
    title: "Tokyo Talkies",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 63.46,
    rating: 4.09,
    stock: 36,
    brand: "Adidas",
    sub_category: "Kids",
    category: "jeans",
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/1485031/pexels-photo-1485031.jpeg?auto=compress&cs=tinysrgb&w=600",
    ],
  },
  {
    id: 4,
    title: "DressBerry",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 20.91,
    rating: 4.3,
    stock: 123,
    brand: "Louis Vuitton",
    sub_category: "Man",
    category: "pants",
    thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/2816480/pexels-photo-2816480.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "https://cdn.dummyjson.com/product-images/4/2.jpg",
      "https://cdn.dummyjson.com/product-images/4/3.jpg",
      "https://cdn.dummyjson.com/product-images/4/4.jpg",
      "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
    ],
  },
  {
    id: 5,
    title: "Zara leather jacket",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 45.58,
    rating: 4.09,
    stock: 32,
    brand: "Louis Vuitton",
    sub_category: "Woman",
    category: "jackets",
    thumbnail: "https://cdn.dummyjson.com/product-images/5/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/2916814/pexels-photo-2916814.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/5/2.jpg",
      "https://cdn.dummyjson.com/product-images/5/3.jpg",
    ],
  },
  {
    id: 6,
    title: "Faux Fur",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "Burberry",
    sub_category: "Kids",
    category: "hoodie",
    thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.png",
    images: [
      "https://images.pexels.com/photos/1187954/pexels-photo-1187954.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/6/2.jpg",
      "https://cdn.dummyjson.com/product-images/6/3.png",
      "https://cdn.dummyjson.com/product-images/6/4.jpg",
    ],
  },
  {
    id: 7,
    title: "Ripped Jeans",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 37.15,
    rating: 4.25,
    stock: 50,
    brand: "Burberry",
    sub_category: "Man",
    category: "jackets",
    thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/2778144/pexels-photo-2778144.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "https://cdn.dummyjson.com/product-images/7/2.jpg",
      "https://cdn.dummyjson.com/product-images/7/3.jpg",
      "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
    ],
  },
  {
    id: 8,
    title: "Jewel Strappy Bralette Top",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 40.23,
    rating: 4.43,
    stock: 68,
    brand: "Nike",
    sub_category: "Woman",
    category: "hoodie",
    thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/2777930/pexels-photo-2777930.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "https://cdn.dummyjson.com/product-images/8/2.jpg",
      "https://cdn.dummyjson.com/product-images/8/3.jpg",
      "https://cdn.dummyjson.com/product-images/8/4.jpg",
      "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
    ],
  },
  {
    id: 9,
    title: "Infinix INBOOK",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 65.83,
    rating: 4.54,
    stock: 96,
    brand: "Nike",
    sub_category: "Kids",
    category: "jackets",
    thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/1857375/pexels-photo-1857375.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/9/2.png",
      "https://cdn.dummyjson.com/product-images/9/3.png",
      "https://cdn.dummyjson.com/product-images/9/4.jpg",
      "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
    ],
  },
  {
    id: 10,
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 60.18,
    rating: 4.43,
    stock: 89,
    brand: "puma",
    sub_category: "Man",
    category: "tshirt",
    thumbnail: "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
    images: [
      "https://images.pexels.com/photos/1018911/pexels-photo-1018911.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/10/2.jpg",
      "https://cdn.dummyjson.com/product-images/10/3.jpg",
      "https://cdn.dummyjson.com/product-images/10/thumbnail.jpeg",
    ],
  },
  {
    id: 11,
    title: "perfume Oil",
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    price: 13,
    discountPercentage: 25.4,
    rating: 4.26,
    stock: 65,
    brand: "puma",
    sub_category: "Woman",
    category: "tshirt",
    thumbnail: "https://cdn.dummyjson.com/product-images/11/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/1759510/pexels-photo-1759510.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/11/2.jpg",
      "https://cdn.dummyjson.com/product-images/11/3.jpg",
      "https://cdn.dummyjson.com/product-images/11/thumbnail.jpg",
    ],
  },
  {
    id: 12,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "Zara",
    sub_category: "Kids",
    category: "shirt",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/1808387/pexels-photo-1808387.jpeg?auto=compress&cs=tinysrgb&w=600",
      "https://cdn.dummyjson.com/product-images/12/2.jpg",
      "https://cdn.dummyjson.com/product-images/12/3.png",
      "https://cdn.dummyjson.com/product-images/12/4.jpg",
      "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    ],
  },
  {
    id: 13,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "puma",
    sub_category: "Man",
    category: "shirt",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/27351166/pexels-photo-27351166/free-photo-of-a-woman-posing-by-the-industrial-construction.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      "https://cdn.dummyjson.com/product-images/12/2.jpg",
      "https://cdn.dummyjson.com/product-images/12/3.png",
      "https://cdn.dummyjson.com/product-images/12/4.jpg",
      "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    ],
  },
  {
    id: 14,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "Zara",
    sub_category: "Woman",
    category: "jeans",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/18213120/pexels-photo-18213120/free-photo-of-woman-posing-in-navy-blue-crop-top-and-black-pants.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "https://cdn.dummyjson.com/product-images/12/2.jpg",
      "https://cdn.dummyjson.com/product-images/12/3.png",
      "https://cdn.dummyjson.com/product-images/12/4.jpg",
      "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    ],
  },
  {
    id: 15,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "puma",
    sub_category: "Kids",
    category: "pants",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/11742017/pexels-photo-11742017.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "https://cdn.dummyjson.com/product-images/12/2.jpg",
      "https://cdn.dummyjson.com/product-images/12/3.png",
      "https://cdn.dummyjson.com/product-images/12/4.jpg",
      "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    ],
  },
  {
    id: 16,
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "Nike",
    sub_category: "Man",
    category: "jackets",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    images: [
      "https://images.pexels.com/photos/18071938/pexels-photo-18071938/free-photo-of-a-woman-in-front-of-a-building.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      "https://cdn.dummyjson.com/product-images/12/2.jpg",
      "https://cdn.dummyjson.com/product-images/12/3.png",
      "https://cdn.dummyjson.com/product-images/12/4.jpg",
      "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
    ],
  },
  {
    id: 17,
    title: "Titleist Tour Performance",
    description: "Titleist Tour Performance Golf Hat - NavyWhite",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "Zara",
    // brand: "Titleist",
    sub_category: "Woman",
    category: "jeans",
    thumbnail:
      "https://images-cdn.ubuy.co.in/654feedacc2a824d172b6ee9-titleist-tour-performance-golf-hat.jpg",
    images: [
      "https://images-cdn.ubuy.co.in/654feedacc2a824d172b6ee9-titleist-tour-performance-golf-hat.jpg",
      "https://images-cdn.ubuy.co.in/663783a6e7e7da6b8f1afddc-titleist-tour-performance-golf-hat.jpg",
      "https://images-cdn.ubuy.co.in/663783a6e7e7da6b8f1afddd-titleist-tour-performance-golf-hat.jpg",
      "https://images-cdn.ubuy.co.in/663783a6e7e7da6b8f1afdde-titleist-tour-performance-golf-hat.jpg",
    ],
  },
  {
    id: 18,
    title: "Stuhrling Original",
    description:
      "New Fashion Bracelet Wrist Watch for Woman Ladies Silver Rose Gold Luxury Gifts",
    price: 40,
    discountPercentage: 55.66,
    rating: 4,
    stock: 52,
    brand: "Nike",
    // brand: "Stuhrling Original",
    sub_category: "Kids",
    category: "jackets",
    thumbnail:
      "https://images-cdn.ubuy.co.in/66248e5c7e620235800f953a-new-fashion-bracelet-wrist-watch-for.jpg",
    images: [
      "https://images-cdn.ubuy.co.in/66248e5c7e620235800f953a-new-fashion-bracelet-wrist-watch-for.jpg",
      "https://images-cdn.ubuy.co.in/66248e5c7e620235800f953d-new-fashion-bracelet-wrist-watch-for.jpg",
      "https://images-cdn.ubuy.co.in/66248e5c7e620235800f9540-new-fashion-bracelet-wrist-watch-for.jpg",
      "https://images-cdn.ubuy.co.in/66248e5c7e620235800f9543-new-fashion-bracelet-wrist-watch-for.jpg",
    ],
  },
];
export default Home;
